alter table "public"."real_estate" add column "name" text not null;

alter table "public"."real_estate" alter column "address" set not null;

alter table "public"."real_estate" alter column "construction_company_id" set not null;

alter table "public"."real_estate" alter column "id" set generated by default;

CREATE UNIQUE INDEX real_estate_address_key ON public.real_estate USING btree (address);

CREATE UNIQUE INDEX real_estate_name_key ON public.real_estate USING btree (name);

alter table "public"."real_estate" add constraint "real_estate_address_key" UNIQUE using index "real_estate_address_key";

alter table "public"."real_estate" add constraint "real_estate_name_key" UNIQUE using index "real_estate_name_key";


