


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."Countries" (
    "country" "text" NOT NULL,
    "cod_country" "text" NOT NULL
);


ALTER TABLE "public"."Countries" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."NumPrefix" (
    "prefix" "text" NOT NULL,
    "cod_country" "text" NOT NULL,
    "id" bigint NOT NULL
);


ALTER TABLE "public"."NumPrefix" OWNER TO "postgres";


COMMENT ON TABLE "public"."NumPrefix" IS 'tabla de prefijos';



ALTER TABLE "public"."NumPrefix" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."NumPrefix_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."RealEstate" (
    "id" bigint NOT NULL,
    "cost" numeric,
    "description" "text",
    "address" "text",
    "zip_code" "text",
    "city" "text",
    "id_document" "text",
    "id_company" "text",
    "stock" numeric
);


ALTER TABLE "public"."RealEstate" OWNER TO "postgres";


COMMENT ON TABLE "public"."RealEstate" IS 'propiedad raíz';



ALTER TABLE "public"."RealEstate" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."RealEstate_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Users" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "surname" "text",
    "address" "text",
    "zip_code" "text",
    "prefix" numeric,
    "phone" numeric,
    "email" "text",
    "city" "text",
    "country" "text",
    "currency" "text",
    "taxes" numeric,
    "income" numeric,
    "job" "text",
    "outcome" numeric,
    "id_type" "text",
    "id_number" numeric,
    "description" "text",
    "cod_country" "text"
);


ALTER TABLE "public"."Users" OWNER TO "postgres";


COMMENT ON TABLE "public"."Users" IS 'tabla de usuarios';



COMMENT ON COLUMN "public"."Users"."cod_country" IS 'foreing key para la tabla de pefijos';



ALTER TABLE "public"."Users" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Users_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."Countries"
    ADD CONSTRAINT "Countries_pkey" PRIMARY KEY ("cod_country");



ALTER TABLE ONLY "public"."NumPrefix"
    ADD CONSTRAINT "NumPrefix_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."RealEstate"
    ADD CONSTRAINT "RealEstate_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Users"
    ADD CONSTRAINT "Users_pkey" PRIMARY KEY ("id");



ALTER TABLE "public"."Countries" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."NumPrefix" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."RealEstate" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Users" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";





































































































































































GRANT ALL ON TABLE "public"."Countries" TO "anon";
GRANT ALL ON TABLE "public"."Countries" TO "authenticated";
GRANT ALL ON TABLE "public"."Countries" TO "service_role";



GRANT ALL ON TABLE "public"."NumPrefix" TO "anon";
GRANT ALL ON TABLE "public"."NumPrefix" TO "authenticated";
GRANT ALL ON TABLE "public"."NumPrefix" TO "service_role";



GRANT ALL ON SEQUENCE "public"."NumPrefix_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."NumPrefix_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."NumPrefix_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."RealEstate" TO "anon";
GRANT ALL ON TABLE "public"."RealEstate" TO "authenticated";
GRANT ALL ON TABLE "public"."RealEstate" TO "service_role";



GRANT ALL ON SEQUENCE "public"."RealEstate_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."RealEstate_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."RealEstate_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Users" TO "anon";
GRANT ALL ON TABLE "public"."Users" TO "authenticated";
GRANT ALL ON TABLE "public"."Users" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Users_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Users_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Users_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";


